version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-push:
    executor: python/default
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t oclettingsv1:${CIRCLE_SHA1} -f ./Dockerfile .
      - run:
          name: Push to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag oclettingsv1:${CIRCLE_SHA1} $DOCKERHUB_USERNAME/oclettingsv1:${CIRCLE_SHA1}
            docker push $DOCKERHUB_USERNAME/oclettingsv1:${CIRCLE_SHA1}
      - run:
          name: Install Heroku CLI
          command: |
            curl https://cli-assets.heroku.com/install.sh | sh
      - run:
          name: Push to Heroku
          command: |
            docker tag oclettingsv1:${CIRCLE_SHA1} registry.heroku.com/oclettingsv1/web
            echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com
            docker push registry.heroku.com/oclettingsv1/web
      - run:
          name: Release to Heroku
          command: |
            heroku container:release web -a oclettingsv1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: main
